# Copyright (c) 2023 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
version: "3.9"
services:
  docker-registry:
    image: registry:latest
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - docker_registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
volumes:
  docker_registry:
    name: docker_registry
