# Copyright (c) 2023 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
version: "3.9"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger-editor
    hostname: swagger-editor
    restart: always
    ports:
      - 8080:8080
