# Copyright (c) 2023 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_lib:/var/lib/mysql
      - mysql_log:/var/log/mysql
      - mysql_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
volumes:
  mysql_lib:
    name: mysql_lib
  mysql_log:
    name: mysql_log
  mysql_conf:
    name: mysql_conf
